GET {{baseUrl}}/api/accounts/

###

GET {{baseUrl}}/api/accounts/example_user2

###

POST {{baseUrl}}/api/accounts
Content-Type: application/json

{
  "userName": "example_user2",
  "email": "user2@example.com",
  "password": "example_password",
  "picture": "example_picture.jpg"
}

###

DELETE {{baseUrl}}/api/accounts/example_user2

