GET {{baseUrl}}/api/accounts

###

GET {{baseUrl}}

###

POST {{baseUrl}}/api/accounts
Content-Type: application/json

{
  "userName": "example_user",
  "email": "user@example.com",
  "password": "example_password",
  "picture": "example_picture.jpg"
}
